# Data Cleansing

In [1]:
%pwd

'/Users/lichao/Library/CloudStorage/OneDrive-Personal/MLD01_Article/Code'

In [2]:
%cd ..

/Users/lichao/Library/CloudStorage/OneDrive-Personal/MLD01_Article

/Users/lichao/opt/anaconda3/envs/ML/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

## Import Package

In [3]:
import os
import pandas as pd

## Dataset 2016

In [8]:
%ls PrivateData/Climate-2016/Data/Data/

HhldLevel_KeyVariable.dta  S07_1.dta
PSULevel_KeyVariable.dta   S07_2.dta
S01.dta                    S08.dta
S02_1.dta                  S09.dta
S02_2.dta                  S10_1.dta
S03.dta                    S10_2.dta
S04.dta                    S10_3.dta
S05.dta                    S11.dta
S06.dta                    S12.dta
S06_4.dta                  Weight.dta

### Meta

In [11]:
df_HhLevel = pd.read_stata("PrivateData/Climate-2016/Data/Data/HhldLevel_KeyVariable.dta")

In [14]:
df_HhLevel

,PSU,HHLD,RespSex,RespAge,RespEdu,Quintl,CZONE
0,101.0,1.0,Female,45-54 Yrs.,Illiterate,Fourth Quintile,Sub-Tropical
1,101.0,2.0,Male,55-64 Yrs.,Primary (1-5),Fifth Quintile (Highest),Sub-Tropical
2,101.0,3.0,Female,45-54 Yrs.,Beginners/Informal edu.,Not Stated,Sub-Tropical
3,101.0,4.0,Male,75+ Yrs.,Beginners/Informal edu.,First Quintile (Lowest),Sub-Tropical
4,101.0,5.0,Male,65-74 Yrs.,Primary (1-5),First Quintile (Lowest),Sub-Tropical
...,...,...,...,...,...,...,...
5055,353.0,16.0,Male,55-64 Yrs.,Bachelor,Third Quintile,Tropical
5056,353.0,17.0,Female,45-54 Yrs.,Illiterate,Fifth Quintile (Highest),Tropical
5057,353.0,18.0,Male,45-54 Yrs.,Illiterate,Fifth Quintile (Highest),Tropical
5058,353.0,19.0,Female,45-54 Yrs.,Illiterate,Third Quintile,Tropical
5059,353.0,20.0,Female,65-74 Yrs.,Illiterate,Fourth Quintile,Tropical

In [15]:
# Categorical summaries
for col in ["RespSex", "RespAge", "RespEdu", "Quintl", "CZONE"]:
    print(f"\n--- {col} ---")
    print(df_HhLevel[col].value_counts(dropna=False))

--- RespSex ---
RespSex
Male      3396
Female    1664
Name: count, dtype: int64

--- RespAge ---
RespAge
45-54 Yrs.    2083
55-64 Yrs.    1522
65-74 Yrs.    1043
75+ Yrs.       412
Name: count, dtype: int64

--- RespEdu ---
RespEdu
Illiterate                 2199
Beginners/Informal edu.     994
Primary (1-5)               645
Lower Sec.(6-8)             338
SLC                         280
Secondary (9-10)            264
Class 12 / Certificate      160
Bachelor                    121
Master and above             59
Name: count, dtype: int64

--- Quintl ---
Quintl
Third Quintile              996
Fourth Quintile             962
Fifth Quintile (Highest)    958
First Quintile (Lowest)     956
Second Quintile             916
Not Stated                  272
Name: count, dtype: int64

--- CZONE ---
CZONE
Tropical        2705
Sub-Tropical    2038
Temperate        297
Sub-Alpine        20
Name: count, dtype: int64

In [17]:
df_PSULevel = pd.read_stata("PrivateData/Climate-2016/Data/Data/PSULevel_KeyVariable.dta")

In [18]:
df_PSULevel

,PSU,Dist,UrbRur71,Strata,EcoBelt,Comb_Vuln,Comb_Risk,Comb_Adap
0,101.0,Taplejung,Rural,Eastern Mountain,Mountain,High,High,Moderate
1,102.0,Taplejung,Urban,Eastern Mountain,Mountain,High,High,Moderate
2,103.0,Taplejung,Rural,Eastern Mountain,Mountain,High,High,Moderate
3,104.0,Taplejung,Rural,Eastern Mountain,Mountain,High,High,Moderate
4,105.0,Taplejung,Rural,Eastern Mountain,Mountain,High,High,Moderate
...,...,...,...,...,...,...,...,...
248,349.0,Kailali,Rural,Far-Western Tarai,Terai,Low,Low,Moderate
249,350.0,Kailali,Urban,Far-Western Tarai,Terai,Low,Low,Moderate
250,351.0,Kailali,Urban,Far-Western Tarai,Terai,Low,Low,Moderate
251,352.0,Kailali,Rural,Far-Western Tarai,Terai,Low,Low,Moderate
252,353.0,Kailali,Urban,Far-Western Tarai,Terai,Low,Low,Moderate

In [19]:
df_PSULevel.columns

Index(['PSU', 'Dist', 'UrbRur71', 'Strata', 'EcoBelt', 'Comb_Vuln',
       'Comb_Risk', 'Comb_Adap'],
      dtype='object')

In [20]:
# Categorical summaries
for col in ['Dist', 'UrbRur71', 'Strata', 'EcoBelt', 'Comb_Vuln', 'Comb_Risk', 'Comb_Adap']:
    print(f"\n--- {col} ---")
    print(df_HhLevel[col].value_counts(dropna=False))

--- Dist ---
Dist
Kathmandu    25
Rupandehi    18
Dang         16
Kailali      14
Dhanusa      14
Rautahat     14
Morang       13
Saptari      13
Achham       12
Dolakha      10
Bajura        9
Salyan        9
Pyuthan       9
Taplejung     9
Dhading       8
Ramechhap     8
Baglung       6
Palpa         6
Panchthar     6
Tanahu        6
Khotang       6
Dhankuta      6
Kaski         6
Jumla         4
Kalikot       4
Mustang       2
Name: count, dtype: int64

--- UrbRur71 ---
UrbRur71
Rural    159
Urban     94
Name: count, dtype: int64

--- Strata ---
Strata
Central Tarai           28
Eastern Tarai           26
Central Hill            24
Western Hill            24
Eastern Hill            18
Western Tarai           18
Mid-Western Hill        18
Kathmandu valley        17
Mid-Western Tarai       16
Far-Western Tarai       14
Far-Western Hill        12
Central Mountain        10
Eastern Mountain         9
Far-Western Mountain     9
Mid-Western Mountain     8
Western Mountain         2
Name: count, dtype: int64

--- EcoBelt ---
EcoBelt
Hill        113
Terai       102
Mountain     38
Name: count, dtype: int64

--- Comb_Vuln ---
Comb_Vuln
High         62
Low          58
Very High    56
Moderate     53
Very Low     24
Name: count, dtype: int64

--- Comb_Risk ---
Comb_Risk
High         82
Moderate     61
Very Low     49
Low          32
Very High    29
Name: count, dtype: int64

--- Comb_Adap ---
Comb_Adap
Moderate     98
Low          54
Very Low     39
Very High    31
High         31
Name: count, dtype: int64

### Data Merging

#### Section 01

In [21]:
df_read = pd.read_stata("PrivateData/Climate-2016/Data/Data/S01.dta")

In [22]:
df_read.shape

(5060, 17)

In [25]:
df_read

,PSU,HHLD,DIST,VDCMUN,WARD,EA,TOLE,A07NME,A07SEX,A07AGE,A08NME,A08SEX,A08AGE,A09,A10,A11,A12
0,101.0,1.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,51.0,Confidential,Female,49.0,Confidenti,Chhetree,Illiterate,49.0
1,101.0,2.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,55.0,Confidential,Male,55.0,Confidenti,Chhetree,Class 5,55.0
2,101.0,3.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,46.0,Confidential,Female,46.0,,Limbu,Literal (Informal edu.),25.0
3,101.0,4.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,78.0,Confidential,Male,78.0,Confidenti,Rai,Literal (Informal edu.),78.0
4,101.0,5.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,70.0,Confidential,Male,70.0,Confidenti,Rai,Class 5,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5055,353.0,16.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,59.0,Confidential,Male,59.0,Confidenti,Kami,Bachelor level,37.0
5056,353.0,17.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Female,52.0,Confidential,Female,52.0,Confidenti,Chhetree,Illiterate,25.0
5057,353.0,18.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,50.0,Confidential,Male,50.0,Confidenti,Musalman,Illiterate,30.0
5058,353.0,19.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Female,50.0,Confidential,Female,50.0,Confidenti,Kami,Illiterate,25.0
5059,353.0,20.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Female,70.0,Confidential,Female,70.0,Confidenti,Chhetree,Illiterate,31.0

In [24]:
df_read.columns

Index(['PSU', 'HHLD', 'DIST', 'VDCMUN', 'WARD', 'EA', 'TOLE', 'A07NME',
       'A07SEX', 'A07AGE', 'A08NME', 'A08SEX', 'A08AGE', 'A09', 'A10', 'A11',
       'A12'],
      dtype='object')

In [26]:
df_read = df_read[['PSU', 'HHLD', 'A07SEX', 'A07AGE', 'A08SEX', 'A08AGE', 'A11', 'A12']]

In [28]:
df_read.columns = ['PSU', 'HHLD', 'HeadHH_Sex', 'HeadHH_Age',
                  'Respon_Sex', 'Respon_Age', 'Edu', 'LivingYear']

In [29]:
df_01 = df_read.copy()

#### Section 02

In [21]:
df_read = pd.read_stata("PrivateData/Climate-2016/Data/Data/S01.dta")

In [22]:
df_read.shape

(5060, 17)

In [25]:
df_read

,PSU,HHLD,DIST,VDCMUN,WARD,EA,TOLE,A07NME,A07SEX,A07AGE,A08NME,A08SEX,A08AGE,A09,A10,A11,A12
0,101.0,1.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,51.0,Confidential,Female,49.0,Confidenti,Chhetree,Illiterate,49.0
1,101.0,2.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,55.0,Confidential,Male,55.0,Confidenti,Chhetree,Class 5,55.0
2,101.0,3.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,46.0,Confidential,Female,46.0,,Limbu,Literal (Informal edu.),25.0
3,101.0,4.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,78.0,Confidential,Male,78.0,Confidenti,Rai,Literal (Informal edu.),78.0
4,101.0,5.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,70.0,Confidential,Male,70.0,Confidenti,Rai,Class 5,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5055,353.0,16.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,59.0,Confidential,Male,59.0,Confidenti,Kami,Bachelor level,37.0
5056,353.0,17.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Female,52.0,Confidential,Female,52.0,Confidenti,Chhetree,Illiterate,25.0
5057,353.0,18.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Male,50.0,Confidential,Male,50.0,Confidenti,Musalman,Illiterate,30.0
5058,353.0,19.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Female,50.0,Confidential,Female,50.0,Confidenti,Kami,Illiterate,25.0
5059,353.0,20.0,0.0,0.0,0.0,0.0,Confidential,Confidential,Female,70.0,Confidential,Female,70.0,Confidenti,Chhetree,Illiterate,31.0

In [24]:
df_read.columns

Index(['PSU', 'HHLD', 'DIST', 'VDCMUN', 'WARD', 'EA', 'TOLE', 'A07NME',
       'A07SEX', 'A07AGE', 'A08NME', 'A08SEX', 'A08AGE', 'A09', 'A10', 'A11',
       'A12'],
      dtype='object')

In [26]:
df_read = df_read[['PSU', 'HHLD', 'A07SEX', 'A07AGE', 'A08SEX', 'A08AGE', 'A11', 'A12']]

In [28]:
df_read.columns = ['PSU', 'HHLD', 'HeadHH_Sex', 'HeadHH_Age',
                  'Respon_Sex', 'Respon_Age', 'Edu', 'LivingYear']

In [29]:
df_01 = df_read.copy()